apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8r
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - update
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - update
