apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8r
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - cronjobs
    verbs:
      - get
      - list
      - update
